# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb14a13d8b4fd95dac9e541abc038191efc21e54e70d2a3f4a44571bdbfea770697305edf1422ff48795caae55b38d9bba9f23be813cf821851a4866af14c59a

test:
  secret_key_base: 3eecb725446a7117c8e134793af460881b078f87c2a01bdbb1996357a2e89b115dbcff6667be76f415f27e9ee256f7465eb3e6ca3e026bcbd16233ded38f151d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
